# Generated by Django 4.2.8 on 2024-01-27 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Register_Login', '0009_paymenttermsupdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerType', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('CustomerDisplayName', models.CharField(max_length=50)),
                ('CompanyName', models.CharField(max_length=100)),
                ('CustomerEmail', models.EmailField(max_length=254)),
                ('CustomerPhone', models.CharField(max_length=20)),
                ('CustomerMobile', models.CharField(max_length=20)),
                ('SkypeName', models.CharField(blank=True, max_length=50, null=True)),
                ('Designation', models.CharField(blank=True, max_length=50, null=True)),
                ('Department', models.CharField(blank=True, max_length=50, null=True)),
                ('Website', models.CharField(blank=True, max_length=100, null=True)),
                ('GSTTreatment', models.CharField(blank=True, max_length=50, null=True)),
                ('GSTNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('PanNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('PlaceOfSupply', models.CharField(blank=True, max_length=50, null=True)),
                ('TaxPreference', models.CharField(blank=True, max_length=50, null=True)),
                ('Currency', models.CharField(blank=True, max_length=5, null=True)),
                ('OpeningBalanceType', models.CharField(max_length=10)),
                ('OpeningBalance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('CreditLimit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('PriceList', models.CharField(blank=True, max_length=50, null=True)),
                ('PortalLanguage', models.CharField(blank=True, max_length=50, null=True)),
                ('Facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('Twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('CurrentBalance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('BillingAttention', models.CharField(max_length=50)),
                ('BillingAddress', models.CharField(max_length=255)),
                ('BillingCity', models.CharField(max_length=50)),
                ('BillingState', models.CharField(max_length=50)),
                ('BillingCountry', models.CharField(max_length=50)),
                ('BillingPinCode', models.CharField(max_length=20)),
                ('BillingMobile', models.CharField(max_length=20)),
                ('BillingFax', models.CharField(max_length=20)),
                ('ShippingAttention', models.CharField(max_length=50)),
                ('ShippingAddress', models.CharField(max_length=255)),
                ('ShippingCity', models.CharField(max_length=50)),
                ('ShippingState', models.CharField(max_length=50)),
                ('ShippingCountry', models.CharField(max_length=50)),
                ('ShippingPinCode', models.CharField(max_length=20)),
                ('ShippingMobile', models.CharField(max_length=20)),
                ('ShippingFax', models.CharField(max_length=20)),
                ('Remarks', models.CharField(max_length=255)),
                ('CustomerStatus', models.CharField(max_length=20)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.zohomodules')),
                ('CompanyPaymentTerms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.paymenttermsupdates')),
                ('LoginDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
            ],
        ),
    ]
