from django.db import models
from Register_Login.models import *

class Customer(models.Model):
    CustomerType = models.CharField(max_length=50)
    Title = models.CharField(max_length=50)
    FirstName = models.CharField(max_length=50)
    LastName = models.CharField(max_length=50)
    CustomerDisplayName = models.CharField(max_length=50)
    CompanyName = models.CharField(max_length=100)
    CustomerEmail = models.EmailField()
    CustomerPhone = models.CharField(max_length=20)
    CustomerMobile = models.CharField(max_length=20)
    SkypeName = models.CharField(max_length=50, null=True, blank=True)
    Designation = models.CharField(max_length=50, null=True, blank=True)
    Department = models.CharField(max_length=50, null=True, blank=True)
    Website = models.CharField(max_length=100, null=True, blank=True)
    GSTTreatment = models.CharField(max_length=50, null=True, blank=True)
    GSTNumber = models.CharField(max_length=50, null=True, blank=True)
    PanNumber = models.CharField(max_length=50, null=True, blank=True)
    PlaceOfSupply = models.CharField(max_length=50, null=True, blank=True)
    TaxPreference = models.CharField(max_length=50, null=True, blank=True)
    Currency = models.CharField(max_length=5, null=True, blank=True)
    OpeningBalanceType = models.CharField(max_length=10)
    OpeningBalance = models.DecimalField(max_digits=18, decimal_places=2)
    CreditLimit = models.DecimalField(max_digits=18, decimal_places=2)
    PriceList = models.CharField(max_length=50, null=True, blank=True)
    PortalLanguage = models.CharField(max_length=50, null=True, blank=True)
    Facebook = models.CharField(max_length=100, null=True, blank=True)
    Twitter = models.CharField(max_length=100, null=True, blank=True)
    CompanyPaymentTerms = models.ForeignKey(PaymentTermsUpdates, on_delete=models.CASCADE)
    CurrentBalance = models.DecimalField(max_digits=18, decimal_places=2)
    BillingAttention = models.CharField(max_length=50)
    BillingAddress = models.CharField(max_length=255)
    BillingCity = models.CharField(max_length=50)
    BillingState = models.CharField(max_length=50)
    BillingCountry = models.CharField(max_length=50)
    BillingPinCode = models.CharField(max_length=20)
    BillingMobile = models.CharField(max_length=20)
    BillingFax = models.CharField(max_length=20)
    ShippingAttention = models.CharField(max_length=50)
    ShippingAddress = models.CharField(max_length=255)
    ShippingCity = models.CharField(max_length=50)
    ShippingState = models.CharField(max_length=50)
    ShippingCountry = models.CharField(max_length=50)
    ShippingPinCode = models.CharField(max_length=20)
    ShippingMobile = models.CharField(max_length=20)
    ShippingFax = models.CharField(max_length=20)
    Remarks = models.CharField(max_length=255)
    CustomerStatus = models.CharField(max_length=20)
    Company = models.ForeignKey(ZohoModules, on_delete=models.CASCADE)
    LoginDetails = models.ForeignKey(CompanyDetails, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.FirstName} {self.LastName}"